apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photo-mosaic.fullname" . }}
  labels:
    {{- include "photo-mosaic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "photo-mosaic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "photo-mosaic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "photo-mosaic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIRECT_URL
              value: {{ required "env.REDIRECT_URL is required" .Values.env.REDIRECT_URL }}
            - name: CALLBACK_URL
              value: {{ required "env.CALLBACK_URL is required" .Values.env.CALLBACK_URL }}
            - name: GOOGLE_CLIENT_ID
              value: {{ required "env.GOOGLE_CLIENT_ID is required" .Values.env.GOOGLE_CLIENT_ID }}
            - name: GOOGLE_CLIENT_SECRET
              value: {{ required "env.GOOGLE_CLIENT_SECRET is required" .Values.env.GOOGLE_CLIENT_SECRET }}
            - name: REDIS_URL
              value: redis://:{{ required "global.redis.password is required" .Values.global.redis.password }}@{{ .Release.Name }}-redis-master:6379
            {{- if .Values.additionalEnv }}
            {{- toYaml .Values.additionalEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.senvoy.enabled }}
        - name: {{ .Chart.Name }}-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.senvoy.repository }}:{{ .Values.senvoy.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.senvoy.pullPolicy }}
          env:
            - name: UPSTREAM_PORT
              value: "3000"
            {{- if .Values.senvoy.additionalEnv }}
            {{- toYaml .Values.senvoy.additionalEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: https
              containerPort: {{ .Values.senvoy.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.senvoy.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.senvoy.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
