#!/bin/bash

WD=$(dirname "$(readlink -f -- "$0")")
PROJECT_NAME=$(basename "${WD}")
DEV_IMAGE=${PROJECT_NAME}-dev
SERVER_IMAGE=${PROJECT_NAME}-server
DOCKER_USER=${DOCKER_USER:-""}
PROD_IMAGE=${DOCKER_USER}/${PROJECT_NAME}-prod
PROD_TAG=latest
PROD_ENV="-e REDIRECT_URL=http://localhost:3000 -e GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} -e GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} -e SESSION_SECRET=${SESSION_SECRET}"
UIDIR=${WD}/ui
SERVERDIR=${WD}/server
SERVER_PORTS="-p 3000:3000"
DOCKER_NET="devnet"
DOCKER_PORTS="-p 5173:5173 -p 24678:24678"
DOCKER_VOLS="-v ${PWD}:${PWD} -w ${PWD}"
DOCKER_USER="--user $(id -u):$(id -g)"

_help() {
  echo "$0"
  echo "Actions:"
  echo "  ui"
  echo "    exec"
  echo "    build"
  echo "  server"
  echo "    exec"
  echo "    build"
  echo "Options:"
  echo ""
}

_setup() {
  if ! docker network ls | grep -q "${DOCKER_NET}"; then
    echo "[INFO] creating docker network ${DOCKER_NET}"
    docker network create "${DOCKER_NET}"
  fi
}

_ui() {
  case "$1" in
    build)
      shift
      echo "Building dev docker image..."
      docker buildx build -f ${UIDIR}/Dockerfile.dev -t ${DEV_IMAGE} ${UIDIR}
      ;;
    exec)
      shift
      _setup
      docker run --rm -it --name ui --net ${DOCKER_NET} ${DOCKER_USER} ${DOCKER_VOLS} ${DOCKER_PORTS} ${DEV_IMAGE} bash
      ;;
    start)
      shift
      cd ${UIDIR}
      yarn dev --host 0.0.0.0
      ;;
  esac
}

_server() {
  case "$1" in
    build)
      shift
      echo "Building server docker image..."
      docker buildx build -f ${SERVERDIR}/Dockerfile.dev -t ${SERVER_IMAGE} ${SERVERDIR}
      ;;
    exec)
      shift
      _setup
      docker run --rm -it --name server --net ${DOCKER_NET} ${DOCKER_USER} ${DOCKER_VOLS} ${SERVER_PORTS} ${SERVER_IMAGE} bash
      ;;
    start)
      shift
      cd ${SERVERDIR}
      node index.js
      ;;
  esac
}

_release() {
  case "$1" in
    build)
      echo "Building release server docker image..."
      docker run --rm -it -v ${PWD}:${PWD} -w ${PWD}/ui --net ${DOCKER_NET} ${DOCKER_USER} ${DOCKER_PORTS} ${DEV_IMAGE} npm run build
      docker buildx build -f ${SERVERDIR}/Dockerfile -t ${PROD_IMAGE}:${PROD_TAG} ${SERVERDIR}
      shift
      ;;
    push)
      shift
      docker push ${PROD_IMAGE}:${PROD_TAG}
      ;;
    start)
      shift
      echo "Starting ${PROD_IMAGE}:${PROD_TAG} docker image..."
      docker run --rm -it ${PROD_ENV} --net ${DOCKER_NET} ${SERVER_PORTS} ${PROD_IMAGE}:${PROD_TAG}
      ;;
    exec)
      shift
      echo "Starting shell ${PROD_IMAGE}:${PROD_TAG} docker image..."
      docker run --rm -it ${PROD_ENV} --net ${DOCKER_NET} ${SERVER_PORTS} ${PROD_IMAGE}:${PROD_TAG} bash
      ;;
  esac
}

_main() {
  case "$1" in
    ui*)
      shift
      _ui "${@}"
      ;;
    serve*)
      shift
      _server "${@}"
      ;;
    rel*)
      shift
      _release "${@}"
      ;;
    *)
      _help;;
  esac
}

args=()
while [[ $# -gt 0 ]]; do
  key="$1"
  case "$key" in
    *)
      args+=("$1")
      shift
      ;;
  esac
done

_main "${args[@]}"
exit 0

