FROM node:alpine

ENV NODE_ENV development

WORKDIR /usr/src/app

RUN apk update --no-cache \
    && apk add vim bash curl

RUN yarn

COPY . .
COPY ./.vimrc /home/node/.vimrc

EXPOSE 5173
EXPOSE 24678

CMD ["yarn", "dev", "--host", "0.0.0.0"]
